apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: chats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: chat-frontend
          image: rupesh1997/chat-service-frontend:1.0.1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: chat-apps
spec:
  selector:
    app: chat-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080