spring:
  config:
    activate:
      on-profile: "production"

info:
  app:
    name: Chat Application Backend
    description: Handles one to one and group chats.
    version: 1.0.0
    profile: production
    owner: Rupesh Dulal
    website: https://www.alfarays.tech
  build:
    timestamp: "@timestamp@"
  developer:
    name: "Rupesh Dulal"
    email: "rupeshdulal672@gmail.com"
    github: "https://github.com/rupeshdulal"